spring:
  application:
    name: demo2
  datasource:
    url: jdbc:mysql://mysql-b-2-service:3306/mydb2
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
app:
  origin: host