spring:
  application:
    name: demo2
  datasource:
    url: jdbc:mysql://localhost:3307/mydb2
    username: root
    password: 1234

app:
  origin: "*"

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,metrics
  metrics:
    tags:
      application: demo2
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: 'true'
  prometheus:
    metrics:
      export:
#        enabled: true
        pushgateway:
          base-url: http://loki-prometheus-pushgateway:9091
logging:
  pattern:
    level: "trace_id=%mdc{trace_id} span_id=%mdc{span_id} trace_flags=%mdc{trace_flags} %p"
